### ISSUE TITLE
No artifacts for version 0.2.11

### ISSUE THREAD

**Issue by aling93** [andreihh/chronolens#1]
Hello Andrei,

I'm trying to build something on top of your work but it looks like there are significant differences between 0.2.10 and 0.2.11. 

My first attempt was to import 0.2.10 using Gradle (which works) but I can't create an InteractiveRepository because I think that GitProxy & JavaParser are not being shipped. 

I worked around by manually copying the .jar files from the 0.2.11 binaries - now I can use InteractiveRepository (I've noticed that in this version it takes a File argument in the constructor) - but it would be great to get this working using Gradle dependency management. 

Thanks!

**Comment by andreihh** [comment]
Hi! I'll try to fix the issues in the next couple of weekends.

**Comment by andreihh** [comment]
Hi! The Jitpack dependency should now work with version 0.2.13. Please let me know if you have any other issues.

Note that I started refactoring the model a bit, I'm trying to enforce type safety with the source node ids rather than using raw strings, but this is still work in progress. You may see some backwards-incompatible changes in that regard in future versions.
